name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  paths-ignore: # 下列文件的变更不触发部署，可以自行添加
    - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.xx
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: npm run build
      # ci 优先使用缓存
      - run: npm ci
      - run: npm run build
      - name: deploy
      - uses: easingthemes/ssh-deploy@v2.0.7
      - env:
       SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          TARGET: ${{ secrets.TARGET }}
